"""add city_id to companies

Revision ID: 2cdcda32cae0
Revises: 69bcbd88a8dd
Create Date: 2026-08-20 09:23:55.597809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdcda32cae0'
down_revision: Union[str, None] = '69bcbd88a8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('city_id', sa.String(length=36), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'city_id', schema='company')
    # ### end Alembic commands ###
