"""drop companies notes column

Revision ID: 6806b605992a
Revises: application_003
Create Date: 2026-08-15 11:27:22.150407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6806b605992a'
down_revision: Union[str, None] = 'application_003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'notes', schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True), schema='company')
    # ### end Alembic commands ###
