"""llm config name unique to user-scoped

Revision ID: efaf28c67af2
Revises: be34d1e87063
Create Date: 2026-09-02 07:47:03.528638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaf28c67af2'
down_revision: Union[str, None] = 'be34d1e87063'
branch_labels: Union[str, Sequence[str], None] = ('ai',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS ai")
    op.drop_constraint(op.f('uq_llm_configurations_name'), 'llm_configurations', schema='ai', type_='unique')
    op.create_unique_constraint('uq_llm_config_name_user', 'llm_configurations', ['name', 'user_id'], schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_llm_config_name_user', 'llm_configurations', schema='ai', type_='unique')
    op.create_unique_constraint(op.f('uq_llm_configurations_name'), 'llm_configurations', ['name'], schema='ai', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
