words = [
    "ADR",
    "ARQ",
    "Checkpointing",
    "EDD",
    "HTTPX",
    "LLM",
    "NATS",
    "cov",
    "dotenv",
    "fastapi",
    "genai",
    "langchain",
    "langgraph",
    "openai",
    "psycopg",
    "pydantic",
    "socketio",
    "structlog",
    "taskiq",
    "typer",
    "uvicorn",
]
