"""add pinned flag to skills

Revision ID: 9d29b936826b
Revises: d5d8d4da3b4c
Create Date: 2026-08-06 19:44:57.415419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d29b936826b'
down_revision: Union[str, None] = 'd5d8d4da3b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'skills',
        sa.Column('pinned', sa.Integer(), nullable=False, server_default='0'),
        schema='skill',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'pinned', schema='skill')
    # ### end Alembic commands ###
