"""change skill name/slug unique to user-scoped

Revision ID: be34d1e87063
Revises: 83d8b3df5482
Create Date: 2026-09-02 07:43:55.378266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be34d1e87063'
down_revision: Union[str, None] = '83d8b3df5482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_skills_name'), 'skills', schema='skill', type_='unique')
    op.drop_index(op.f('ix_skill_skills_slug'), table_name='skills', schema='skill')
    op.create_index(op.f('ix_skill_skills_slug'), 'skills', ['slug'], unique=False, schema='skill')
    op.create_unique_constraint('uq_skill_name_user', 'skills', ['name', 'user_id'], schema='skill')
    op.create_unique_constraint('uq_skill_slug_user', 'skills', ['slug', 'user_id'], schema='skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_skill_slug_user', 'skills', schema='skill', type_='unique')
    op.drop_constraint('uq_skill_name_user', 'skills', schema='skill', type_='unique')
    op.drop_index(op.f('ix_skill_skills_slug'), table_name='skills', schema='skill')
    op.create_index(op.f('ix_skill_skills_slug'), 'skills', ['slug'], unique=True, schema='skill')
    op.create_unique_constraint(op.f('uq_skills_name'), 'skills', ['name'], schema='skill', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
