"""add skill_mentions table

Revision ID: d5d8d4da3b4c
Revises: company_006_normalize_intelligence_score_keys
Create Date: 2026-08-06 17:44:27.022048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d8d4da3b4c'
down_revision: Union[str, None] = 'company_006_normalize_intelligence_score_keys'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skills.id'], name=op.f('fk_skill_mentions_skill_id_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_mentions')),
    sa.UniqueConstraint('skill_id', 'source_type', 'source_id', name=op.f('uq_skill_mentions_skill_id')),
    schema='skill'
    )
    op.create_index(op.f('ix_skill_mentions_skill_id'), 'skill_mentions', ['skill_id'], unique=False, schema='skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_mentions_skill_id'), table_name='skill_mentions', schema='skill')
    op.drop_table('skill_mentions', schema='skill')
    # ### end Alembic commands ###
