"""add skill categories catalog and links

Revision ID: skill_002
Revises: 492885f00b29
Create Date: 2026-08-08 09:50:25.600236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'skill_002'
down_revision: Union[str, None] = '492885f00b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CANONICAL_CATEGORIES = ("technical", "engineering", "professional", "domain", "career")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_skill_categories_name')),
    schema='skill'
    )
    op.create_table('skill_category_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['skill.skill_categories.id'], name=op.f('fk_skill_category_links_category_id_skill_categories')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skills.id'], name=op.f('fk_skill_category_links_skill_id_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_category_links')),
    sa.UniqueConstraint('skill_id', 'category_id', name=op.f('uq_skill_category_links_skill_id')),
    schema='skill'
    )
    # ### end Alembic commands ###

    # Seed the canonical category catalog (task 126).
    bind = op.get_bind()
    for name in CANONICAL_CATEGORIES:
        bind.execute(
            sa.text(
                "INSERT INTO skill.skill_categories (name, created_at) "
                "VALUES (:name, CURRENT_TIMESTAMP) "
                "ON CONFLICT (name) DO NOTHING"
            ),
            {"name": name},
        )

    # Backfill: create a catalog row for every legacy primary category value,
    # then link each visible skill to its category.
    bind.execute(
        sa.text(
            "INSERT INTO skill.skill_categories (name, created_at) "
            "SELECT DISTINCT s.category, CURRENT_TIMESTAMP "
            "FROM skill.skills s "
            "WHERE s.category <> '' "
            "ON CONFLICT (name) DO NOTHING"
        )
    )
    bind.execute(
        sa.text(
            "INSERT INTO skill.skill_category_links (skill_id, category_id, created_at) "
            "SELECT s.id, c.id, CURRENT_TIMESTAMP "
            "FROM skill.skills s "
            "JOIN skill.skill_categories c ON c.name = s.category "
            "WHERE s.category <> '' "
            "ON CONFLICT (skill_id, category_id) DO NOTHING"
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_category_links', schema='skill')
    op.drop_table('skill_categories', schema='skill')
    # ### end Alembic commands ###
