"""roadmap: initial roadmap schema

Revision ID: roadmap_001
Revises: application_001
Create Date: 2026-08-12 11:31:27.115143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'roadmap_001'
down_revision: Union[str, None] = 'application_001'
branch_labels: Union[str, Sequence[str], None] = ('roadmap',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS roadmap")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmaps')),
    schema='roadmap'
    )
    op.create_index(op.f('ix_roadmap_roadmaps_application_id'), 'roadmaps', ['application_id'], unique=False, schema='roadmap')
    op.create_table('roadmap_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_job_id', sa.String(length=36), nullable=True),
    sa.Column('target_company_id', sa.String(length=36), nullable=True),
    sa.Column('target_skill_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.roadmaps.id'], name=op.f('fk_roadmap_goals_roadmap_id_roadmaps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_goals')),
    schema='roadmap'
    )
    op.create_index(op.f('ix_roadmap_roadmap_goals_roadmap_id'), 'roadmap_goals', ['roadmap_id'], unique=False, schema='roadmap')
    op.create_table('roadmap_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.roadmaps.id'], name=op.f('fk_roadmap_milestones_roadmap_id_roadmaps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_milestones')),
    schema='roadmap'
    )
    op.create_index(op.f('ix_roadmap_roadmap_milestones_roadmap_id'), 'roadmap_milestones', ['roadmap_id'], unique=False, schema='roadmap')
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('estimated_effort', sa.String(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['roadmap.roadmap_milestones.id'], name=op.f('fk_roadmap_tasks_milestone_id_roadmap_milestones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_tasks')),
    schema='roadmap'
    )
    op.create_index(op.f('ix_roadmap_roadmap_tasks_milestone_id'), 'roadmap_tasks', ['milestone_id'], unique=False, schema='roadmap')
    op.create_table('roadmap_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['roadmap.roadmap_milestones.id'], name=op.f('fk_roadmap_notes_milestone_id_roadmap_milestones')),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.roadmaps.id'], name=op.f('fk_roadmap_notes_roadmap_id_roadmaps')),
    sa.ForeignKeyConstraint(['task_id'], ['roadmap.roadmap_tasks.id'], name=op.f('fk_roadmap_notes_task_id_roadmap_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_notes')),
    schema='roadmap'
    )
    op.create_index(op.f('ix_roadmap_roadmap_notes_roadmap_id'), 'roadmap_notes', ['roadmap_id'], unique=False, schema='roadmap')
    op.create_table('roadmap_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['roadmap.roadmap_milestones.id'], name=op.f('fk_roadmap_resources_milestone_id_roadmap_milestones')),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.roadmaps.id'], name=op.f('fk_roadmap_resources_roadmap_id_roadmaps')),
    sa.ForeignKeyConstraint(['task_id'], ['roadmap.roadmap_tasks.id'], name=op.f('fk_roadmap_resources_task_id_roadmap_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_resources')),
    schema='roadmap'
    )
    op.create_index(op.f('ix_roadmap_roadmap_resources_roadmap_id'), 'roadmap_resources', ['roadmap_id'], unique=False, schema='roadmap')
    op.create_table('roadmap_skill_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['roadmap.roadmap_milestones.id'], name=op.f('fk_roadmap_skill_links_milestone_id_roadmap_milestones')),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.roadmaps.id'], name=op.f('fk_roadmap_skill_links_roadmap_id_roadmaps')),
    sa.ForeignKeyConstraint(['task_id'], ['roadmap.roadmap_tasks.id'], name=op.f('fk_roadmap_skill_links_task_id_roadmap_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_skill_links')),
    schema='roadmap'
    )
    op.create_index(op.f('ix_roadmap_roadmap_skill_links_roadmap_id'), 'roadmap_skill_links', ['roadmap_id'], unique=False, schema='roadmap')
    op.create_index(op.f('ix_roadmap_roadmap_skill_links_skill_id'), 'roadmap_skill_links', ['skill_id'], unique=False, schema='roadmap')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_roadmap_skill_links_skill_id'), table_name='roadmap_skill_links', schema='roadmap')
    op.drop_index(op.f('ix_roadmap_roadmap_skill_links_roadmap_id'), table_name='roadmap_skill_links', schema='roadmap')
    op.drop_table('roadmap_skill_links', schema='roadmap')
    op.drop_index(op.f('ix_roadmap_roadmap_resources_roadmap_id'), table_name='roadmap_resources', schema='roadmap')
    op.drop_table('roadmap_resources', schema='roadmap')
    op.drop_index(op.f('ix_roadmap_roadmap_notes_roadmap_id'), table_name='roadmap_notes', schema='roadmap')
    op.drop_table('roadmap_notes', schema='roadmap')
    op.drop_index(op.f('ix_roadmap_roadmap_tasks_milestone_id'), table_name='roadmap_tasks', schema='roadmap')
    op.drop_table('roadmap_tasks', schema='roadmap')
    op.drop_index(op.f('ix_roadmap_roadmap_milestones_roadmap_id'), table_name='roadmap_milestones', schema='roadmap')
    op.drop_table('roadmap_milestones', schema='roadmap')
    op.drop_index(op.f('ix_roadmap_roadmap_goals_roadmap_id'), table_name='roadmap_goals', schema='roadmap')
    op.drop_table('roadmap_goals', schema='roadmap')
    op.drop_index(op.f('ix_roadmap_roadmaps_application_id'), table_name='roadmaps', schema='roadmap')
    op.drop_table('roadmaps', schema='roadmap')
    # ### end Alembic commands ###
